### ISSUE TITLE
Auto reload not working 

### ISSUE THREAD

**Issue by nkb-bd** [blonestar/wp-theme-vite-tailwind-jit#2]

**Comment by blonestar** [comment]
So you solved the issue?
I just saw emails.

**Comment by nkb-bd** [comment]
Yes solved, but I think it needs to be more efficient , check this
https://github.com/8bit-echo/sage-vite , the dev env changing from npm
command and the vite asset loader.

**Comment by blonestar** [comment]
Will check that, thanks.
