### ISSUE TITLE
Security - functions.php and inc.vite.php

### ISSUE THREAD

**Issue by amazingsey** [blonestar/wp-theme-vite-tailwind-jit#4]
Hello,

Thank you for your Boilerplate Wordpress Theme. I found it useful.
Suggestion, please could you consider including the snippets below
`defined( 'ABSPATH' ) || exit;`
in both functions.php and inc.vite.php for security reasons.

Thank you.

**Comment by blonestar** [comment]
This is just my example how to use ViteJS in Wordpress theme development, but sure I can. :)
Thanks for the feedback.

**Comment by blonestar** [comment]
Done, thank you
