### ISSUE TITLE
after NPM run dev

### ISSUE THREAD

**Issue by andresclua** [blonestar/wp-theme-vite-tailwind-jit#6]
After installing, I run `npm run dev` and I've got this, what I'm missing ? 

<img width="818" alt="Captura de Pantalla 2022-10-18 a la(s) 22 26 38" src="https://user-images.githubusercontent.com/612806/196536876-5dded23d-8b9d-4705-be48-3f73ff04b826.png">

**Comment by blonestar** [comment]
You should run local web server as usual and website on the local domain eg http://your-website.local.
That is just HMR connection for live reload which function in the background.

**Comment by andresclua** [comment]
hey @blonestar, TSM!

**Comment by fedeweb** [comment]
Hi @blonestar,

thanks for your work. I'm using your setup and it's working great.

I always set a virtual host for my projects (for example name.site) and with my previous configuration, with Gulp and Webpack, I was able to access to the website from external device by using my IP network.

How can I do the same thing with vite and your configuration?
